spring:
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB
  datasource:
    url: jdbc:postgresql://awseb-e-rzcbmpibtp-stack-awsebrdsdatabase-d04lzfuazfrd.c9tkfz4bm0mm.eu-central-1.rds.amazonaws.com:5432/postgres
    username: nicusor
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

security:
  secret-key: "KZ87wAMYYyVByiy6JoXkrKrldECv2Sbi"

admin:
  email: "admin@example.com"
  password: "password"

aws:
  region: "eu-central-1"
  s3:
    mock: false
    bucket:
      name: "school-management-system"